[package]
name = "rafka_core"
version = "0.1.0"
authors = ["Seb Ospina <kraige@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slog = "2.7.0"
slog-term = "2.6.0"
futures = "0.3.8"
tokio = { version = "1", features = ["full"] }
failure = "0.1.8"
tracing = "0.1.22"
tracing-futures = "0.2.4"
tracing-log = { version = "0.1.1", features = ["env_logger"] }
tracing-attributes = "0.1.11"
java-properties = "1.3.0"
env_logger = "0.8.2"
test-env-log = "0.2.3"
zookeeper-async = "3.0.0"
thiserror = "1.0"
fs-err = "2.5"

[dev-dependencies]
test-env-log = { version = "0.2.3", features = ["trace"] }
env_logger = "0.8.2"
tracing-subscriber = { version = "0.2.15", features = ["chrono", "env-filter", "fmt"] }
