[package]
name = "rafka_core"
version = "0.1.0"
authors = ["Seb Ospina <kraige@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slog = "2.5.2"
slog-term = "2.6.0"
futures = "0.3"
tokio = { version = "0.2", features = ["full"] }
joyent-tokio-zookeeper = { path = "../tokio-zookeeper" }
failure = "0.1"
tracing = "0.1"
tracing-futures = "0.2"
