[package]
name = "rafka_core"
version = "0.1.0"
authors = ["Seb Ospina <kraige@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slog-term = "2.6.0"
futures = "0.1"
tokio = "0.1"
tokio-zookeeper = "0.1"
failure = "0.1"
