[package]
name = "deriver"
version = "0.1.0"
authors = ["Seb Ospina <kraige@gmail.com>"]
edition = "2021"

[dependencies]
enum-iterator = "0.7.0"

[dependencies.rafka_derive]
path = "../rafka_derive"

[dependencies.rafka_core]
path = "../rafka_core"
